### PR TITLE
[SAM] Add undo button and background point mode

### PR DESCRIPTION
**Pull request by radames**
Demo Updated: https://huggingface.co/spaces/radames/candle-segment-anything-wasm

### CODE REVIEW

**Comment by LaurentMazare** [comment]
Looks amazing!
Two suggestions though happy to defer to subsequent PR if you prefer:
- Could we use different colors for the background and "normal" points (both appear cyan to me)?
- Maybe when clicking close enough to an existing point, the point gets removed rather than a new point added?

**Comment by radames** [comment]
thanks for the feedback! can send the changes on this PR. I like the idea of removing the point if it's close enough. I'll keep the same button to toggle modes and add the remove feature

**Comment by radames** [comment]
very neat idea @LaurentMazare , you can test it now, the distance is about 3 pixels radius.

**Comment by radames** [comment]
Before you merge, I'll add a shift click for desktop as well!

**Comment by LaurentMazare** [comment]
Works very nicely, let me know when good to merge!

**Comment by radames** [comment]
it looks good now @LaurentMazare thanks

**Review by LaurentMazare — APPROVED** [review]

**Pull request merged**
