### PR TITLE
Quant t5: Add coedit model to wasm demo and readme

### PR DESCRIPTION
**Pull request by jbochi**
Hey @LaurentMazare . Thanks for reviewing and merging https://github.com/huggingface/candle/pull/1029 so quickly.

As you [suggested](https://github.com/huggingface/candle/pull/1029#issuecomment-1747213867), this updates the [readme of the example](https://github.com/huggingface/candle/tree/main/candle-examples/examples/quantized-t5) and also the wasm demo.

I tested it locally:

image

I'll see what I can do about advertising this. Creating a quantized model and running it in the browser with Candle was surprisingly easy!

### CODE REVIEW

**Review by radames — APPROVED** [review]
Very cool! just test it, powerful model! The generation is a bit slow, however the model is ~643mb 

the demos is updated 
https://huggingface.co/spaces/radames/Candle-T5-Generation-Wasm

**Comment by LaurentMazare** [comment]
Great @jbochi thanks for the PR and @radames thanks for looking at it. If it's `q6k` quantized, might be worth trying `q4k` or `q4_0` too for a much smaller model (`q4_0` is less precise but has the nice advantage that it works with tensors that have much smaller shape whereas `q6k` would just silently not quantize them).

**Comment by LaurentMazare** [comment]
Certainly a good idea to try the other formats. Also worth mentioning that @LLukas22 has been pushing on some changes that should make it a lot easier to investigate more complex quantization schemes (i.e. changing the quantization type depending on the layer "height" in the model) and evaluate the resulting model perplexity. Hopefully this will allow for more easily finding the optimal way to do quantization.

**Comment by jbochi** [comment]
Having a simple way to tune and evaluate quantization automatically sounds excellent!

I created this space to try the different formats:  https://huggingface.co/spaces/jbochi/Candle-CoEdIT-Wasm

4k and 4_0 are ~2x faster, and I didn't notice any quality issues.

The 4k XL (1.6GB) model also runs in my browser, whereas the 6k XL version is too big (2.34GB).

**Comment by radames** [comment]
oh 400mb and still good! 👏

**Comment by radames** [comment]
tweet about it! @jbochi I hope that's you :) https://twitter.com/radamar/status/1709781748509446647

**Pull request merged**
