### PR TITLE
More Model Module Docs

### PR DESCRIPTION
**Pull request by zachcp**
As per Discord discussion, continuing to update the model docs.

image
image
image
image

### CODE REVIEW

**Review by LaurentMazare — APPROVED** [review]

**Comment by LaurentMazare** [comment]
There seems to be some clippy errors in the CI. Could you have a look?

**Comment by zachcp** [comment]
( yep. but AFK )

**Comment by zachcp** [comment]
New error is in unintended eval of markdown block. will look into fix

```
//! ```no_run
//! // for sentence embeddings
//! # use candle_core::Tensor;
//! # use candle_nn::{VarBuilder, Module};
//! # fn main() -> candle_core::Result<()> {
//! # let model = todo!();
```

**Comment by zachcp** [comment]
To have text highlighting without execution you can use the following:

```
//! ```rust,text
```

**Comment by zachcp** [comment]
This error is unrelated to my PR. I believe it may have been introduced in  #2618 

image


```sh
error: failed to run custom build command for `pyo3-build-config v0.22.6`
Error: failed to run custom build command for `pyo3-build-config v0.22.6`
Caused by:
  process didn't exit successfully: `D:\a\candle\candle\target\debug\build\pyo3-build-config-54d91561316d6713\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=PYO3_CONFIG_FILE
  cargo:rerun-if-env-changed=PYO3_NO_PYTHON
  cargo:rerun-if-env-changed=PYO3_ENVIRONMENT_SIGNATURE
  cargo:rerun-if-env-changed=PYO3_PYTHON
  cargo:rerun-if-env-changed=VIRTUAL_ENV
  cargo:rerun-if-env-changed=CONDA_PREFIX
  cargo:rerun-if-env-changed=PATH

  --- stderr
  error: cannot set a minimum Python version 3.11 higher than the interpreter version 3.9 (the minimum Python version is implied by the abi3-py311 feature)
warning: build failed, waiting for other jobs to finish...
```

**Comment by zachcp** [comment]
Bumped the gh-action ci to python 3.11/

**Comment by zachcp** [comment]
Hmmm.... still failing on Windows due to python version incompatibility


image

**Comment by zachcp** [comment]
from pyo3:  https://github.com/PyO3/pyo3/blob/main/.github/workflows/ci.yml 

```
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install --upgrade pip && pip install nox
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check python formatting and lints (ruff)
        run: nox -s ruff
      - name: Check rust formatting (rustfmt)
        run: nox -s rustfmt
```

**Comment by zachcp** [comment]
Ok. `windows:Check` passes but I missed `Windows:test`.  Updated. should now all pass.

**Pull request merged**
