### PR TITLE
Add ESRGAN-candle-rs example to README

### PR DESCRIPTION
**Pull request by joeyballentine**
As per #1342, I have added my repo to the README as an external resource. If there's a better place to put it, let me know.

Feel free to close this and just yoink the code into candle as an official CLI example with whatever modifications you want to make, I don't mind. (you'll probably wanna clean up my code though lol)

### CODE REVIEW

**Comment by LaurentMazare** [comment]
Would you mind adding some input/output images in your own repo readme that would have been generated via the candle model? Would be a great way to illustrate how well this works!

**Comment by joeyballentine** [comment]
I unfortunately ran out of time and now don't have time to find and make some good test example images. Perhaps I should have linked the original ESRGAN/RealESRGAN repos...

Results are also heavily dependent on what weights you use. There's tons of ESRGAN and Compact models available online (for example on openmodeldb.info), and all of those should work with my repo.

Anyway, feel free to close this for now and I can reopen this in the future once I've added some examples

**Comment by LaurentMazare** [comment]
Closing this as no recent updates.

**Comment by joeyballentine** [comment]
Sorry for never finishing this. Honestly, I just forgot about this PR. I might come back to update the repo in the future, in which case if i add some examples i'll reopen this.

**Pull request closed without merging**
