### PR TITLE
Adding bfloat16 support for the cast kernels.

### PR DESCRIPTION
**Pull request by Narsil**
```
cargo run --example mistral --release --features metal -- --model-id mistralai/Mistral-7B-Instruct-v0.2 --prompt 'Write hello world code in Rust' --sample-len 1
```

### CODE REVIEW

**Review by Vaibhavs10 — COMMENTED** [review]
Not sure what's wrong but for me it's stuck here:

```
cargo run --example mistral --release --features metal -- --model-id mistralai/Mistral-7B-Instruct-v0.2 --prompt 'Write hello world code in Rust' --sample-len 100
    Finished release [optimized] target(s) in 0.86s
     Running `/Users/vb/Documents/hf_projects/candle/target/release/examples/mistral --model-id mistralai/Mistral-7B-Instruct-v0.2 --prompt 'Write hello world code in Rust' --sample-len 100`
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 15.481208ms
loaded the model in 57.919919125s
Write hello world code in Rust
```

**Comment by Vaibhavs10** [comment]
I get the same on CPU (after removing `--features metal`)

```
cargo run --example mistral --release -- --model-id mistralai/Mistral-7B-Instruct-v0.2 --prompt 'Write hello world code in Rust' --sample-len 100
   Compiling candle-nn v0.3.3 (/Users/vb/Documents/hf_projects/candle/candle-nn)
   Compiling candle-transformers v0.3.3 (/Users/vb/Documents/hf_projects/candle/candle-transformers)
   Compiling candle-datasets v0.3.3 (/Users/vb/Documents/hf_projects/candle/candle-datasets)
   Compiling candle-examples v0.3.3 (/Users/vb/Documents/hf_projects/candle/candle-examples)
    Finished release [optimized] target(s) in 11.88s
     Running `/Users/vb/Documents/hf_projects/candle/target/release/examples/mistral --model-id mistralai/Mistral-7B-Instruct-v0.2 --prompt 'Write hello world code in Rust' --sample-len 100`
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 22.795792ms
Running on CPU, to run on GPU(metal), build this example with `--features metal`
loaded the model in 46.910336042s
Write hello world code in Rust
```

**Comment by Narsil** [comment]
> loaded the model in 57.919919125s

Wow this is slow. It's probably not stuck just slow to perform the first matmul. (I'm getting 7 tok/s personally)

**Comment by Vaibhavs10** [comment]
Yeah! I'm not sure what went wrong. I'll flush the cache and double-check again.

**Comment by Vaibhavs10** [comment]
Hmm. after purging. something is definitely not right: It is taking 27GB RAM.

That sounds excessive for a 7B model no?

image

**Comment by Vaibhavs10** [comment]
With llama 7B I get 3.16 tok/sec - so deffo something wrong with Mistral 7B example. @Narsil 

```
cargo run --example llama --release --features metal -- --model-id meta-llama/Llama-2-7b-hf --prompt 'Write hello world code in Rust' --sample-len 100
   Compiling candle-metal-kernels v0.3.3 (/Users/vb/Documents/hf_projects/candle/candle-metal-kernels)
   Compiling candle-core v0.3.3 (/Users/vb/Documents/hf_projects/candle/candle-core)
   Compiling candle-nn v0.3.3 (/Users/vb/Documents/hf_projects/candle/candle-nn)
   Compiling candle-datasets v0.3.3 (/Users/vb/Documents/hf_projects/candle/candle-datasets)
   Compiling candle-transformers v0.3.3 (/Users/vb/Documents/hf_projects/candle/candle-transformers)
   Compiling candle-examples v0.3.3 (/Users/vb/Documents/hf_projects/candle/candle-examples)
    Finished release [optimized] target(s) in 24.33s
     Running `/Users/vb/Documents/hf_projects/candle/target/release/examples/llama --model-id meta-llama/Llama-2-7b-hf --prompt 'Write hello world code in Rust' --sample-len 100`
loading the model weights from meta-llama/Llama-2-7b-hf
tokenizer.json [00:00:01] [██████████████████] 1.76 MiB/1.76 MiB 1.56 MiB/s (0s)
config.json [00:00:00] [███████████████████████████] 609 B/609 B 1.35 KiB/s (0s)
model.safetensors.index.json [00:00:00] [█] 26.16 KiB/26.16 KiB 68.62 KiB/s (0s)
..del-00002-of-00002.safetensors [00:02:24] [] 3.26 GiB/3.26 GiB 23.17 MiB/s (0s)..del-00001-of-00002.safetensors [00:00:00] [░░░░░░░░░░] 0 B/9.29 GiB 0 B/s (0s
..del-00001-of-00002.safetensors [00:06:53] [] 9.29 GiB/9.29 GiB 23.04 MiB/s (0s)building the model
starting the inference loop
Write hello world code in Rust

I'm trying to write a hello world program in Rust. I'm using the Rust Playground.

I've tried to write the following code:

\begin{code}
fn main() {
    println!("Hello, world!");
}
\end{code}

But I get the following error:

\begin{code}
error[E0277]: the trait bound `main::main: std

100 tokens generated (3.16335420760559 token/s)
```

**Pull request merged**
