### PR TITLE
make llama2 derive clone

### PR DESCRIPTION
**Pull request by danielclough**
Added derive Clone so that I can pass the model around my app in State.
Added derive Debug because that's what is used in other models.

### CODE REVIEW

**Comment by LaurentMazare** [comment]
I think for these models it's pretty error prone to clone them as they embed a kv cache that is accessed via inner mutability. So if you clone them, the cache would be shared between the two instances and very likely to conflict. Are you sure that this would not result in a bug in your use case too?

**Comment by danielclough** [comment]
Ah.
That explains the bug when I use `kv_cache` `true`.

Running with `kv_cache` `false` works as expected.

Do you have any suggestions for passing models around in Axum `State` (`Mutex`) other than cloning them?

**Comment by LaurentMazare** [comment]
I've pushed some tweaks to make the llama2 and quantized-llama2 models use an explicit cache rather than internalizing it, this removes the need for a mutex so cloning these should be safer now.

**Comment by danielclough** [comment]
Fantastic!

**Pull request closed without merging**
