### PR TITLE
fix: add missing gpu fill kernels

### PR DESCRIPTION
**Pull request by grzuy**

### CODE REVIEW

**Review by LaurentMazare — APPROVED** [review]

**Comment by LaurentMazare** [comment]
Oh that's certainly embarassing. Thanks for spotting these and making the fix. Could you just confirm that you've run something like `cuda test --features cuda`? (I'm away from my desktop computer at the moment so cannot run cuda stuff easily)

**Comment by grzuy** [comment]
I did :-)

```
$ cargo test ones_gpu --features cuda

[...]

running 1 test
test ones_gpu ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 54 filtered out; finished in 0.20s
```

**Comment by LaurentMazare** [comment]
Amazing, thanks!

**Comment by grzuy** [comment]
Thank you!

**Pull request merged**
