### PR TITLE
Little docs changes

### PR DESCRIPTION
**Pull request by Ssslakter**
Closes https://github.com/huggingface/candle/issues/680 

This pr basically is a little documentation fix to make example working straight from copy-pasting them and changing the device to cuda.

### CODE REVIEW

**Review by LaurentMazare — APPROVED** [review]

**Comment by LaurentMazare** [comment]
It seems that your `Cargo.toml` change renaming `candle` to `candle-core` is actually breaking a few things in the clippy CI. Could you have a look?

**Comment by Ssslakter** [comment]
Ok, this is interesting, I tried to run the `mdbook test -L ..\target\release\deps` on this chapter and it only worked after I changed the name to `candle-core`. I haven't noticed the imports in `lib.rs`. My guess is that it is breaking since docs use `extern crate candle_core;` and tests use  `use candle;` so different names break one of these. Maybe we should make the imports in the docs and `lib.rs` consistent, so we have everywhere `use candle;` or everywhere `use candle_core;` ?

**Comment by LaurentMazare** [comment]
Sounds right, I would suggest `candle` everywhere (as we're doing in all examples etc) though not a very strong opinion here.

**Comment by Ssslakter** [comment]
Well... I believe I would have to keep it as it was before. Probably has to do with how rustdoc uses compiled libraries

**Review by LaurentMazare — APPROVED** [review]

**Comment by LaurentMazare** [comment]
Ah there still seems to be some CI issues, this time in the "Test candle-book" which is probably relevant :) Would you mind having another look?

**Comment by LaurentMazare** [comment]
Looks good now, thanks for the PR and sorry for all the back and forth!

**Comment by Ssslakter** [comment]
Whoops, I accidently forgot to replace to random in this line https://github.com/huggingface/candle/blob/main/candle-book/src/guide/hello_world.md?plain=1#L32 
Omg, how silly to make a mistake in that simple😅 
@LaurentMazare I could make a new one-line pr or it seems would be better to edit this line alongside with other future documentation changes

**Comment by LaurentMazare** [comment]
1 line PR is good if you have the time for it (otherwise I'll make it on my side, pretty sure I would forget about it if not addressed now :) ).

**Comment by Ssslakter** [comment]
Good! Here it is https://github.com/huggingface/candle/pull/804 🤗

**Pull request merged**
