### PR TITLE
Add the ChatGLM model.

### PR DESCRIPTION
**Pull request by LaurentMazare**

### CODE REVIEW

**Comment by overheat** [comment]
CI fail on Windows. so close.

**Comment by LaurentMazare** [comment]
Actually the issue is not really the windows CI (which is flaky) but rather that there is no tokenizer config file that would work with the `tokenizer` crate

**Comment by overheat** [comment]
merge?

**Comment by LaurentMazare** [comment]
> merge?

There is still no "fast tokenizer" config for this I'm afraid. I think there was a request on [this github issue](https://github.com/THUDM/ChatGLM3/issues/122) but unsure if anything happened (and cannot really read what is going on here).

**Comment by guoqingbao** [comment]
> > merge?
> 
> There is still no "fast tokenizer" config for this I'm afraid. I think there was a request on [this github issue](https://github.com/THUDM/ChatGLM3/issues/122) but unsure if anything happened (and cannot really read what is going on here).

**New updates**: I have requested them to provide tokenizer.json file for candle, they have done the revision of fast tokenizer today to generate tokenizer. json which can be loaded in candle (they claimed). I also asked them for uploading tokenizer.json to huggingface repo. Perhaps we can also generate the json file by ourselves in case of the delayed uploads (Chinese spring festival holiday).

For your reference: 
https://huggingface.co/THUDM/chatglm3-6b/discussions/12

**Comment by guoqingbao** [comment]
The updated code for generating the tokenizer.json file:

https://huggingface.co/THUDM/chatglm3-6b/discussions/12#654e149cd0cfd9cb3f7cd6bc

**Pull request merged**
