### PR TITLE
Add `from_tensors` method to `VarMap`

### PR DESCRIPTION
**Pull request by EricLBuehler**
Hello everybody,

In this PR, I added a from_tensors method to VarMap to allow more flexible usage. In addition, I incorporated my previous changes in which I added the `typos` utility to CI.

This method takes a HashMap of tensors and converts it to a HashMap of Vars before returning the resulting VarMap. This function allows loading a VarMap more flexibly.

Thank you!
Eric

### CODE REVIEW

**Comment by EricLBuehler** [comment]
I noticed that some of the checks have failed, those are because AWS credentials could not be loaded.

**Comment by EricLBuehler** [comment]
@LaurentMazare , do you have any thoughts on why my PR AWS workflows keep failing while others do not? I just did a standard fork and PR.

**Comment by EricLBuehler** [comment]
Right, and this only adds an instantiation function to VarMap.

**Comment by Narsil** [comment]
Only admins on this repo will get access to the CI credentials for the GPU, meaning the test will normally fail for all contributors.

This is acceptable tradeoff for now (Since the CI is accessing HF internal compute).
We'll see about longer term CI in the midterm.

**Comment by EricLBuehler** [comment]
Closed due to #894

**Pull request closed without merging**
