### PR TITLE
Metal: i64 basic support

### PR DESCRIPTION
**Pull request by grzuy**
Plan to complete with at least the same i64 support current in cuda kernels.

### CODE REVIEW

**Review by Narsil — APPROVED** [review]
LGTM

**Comment by Narsil** [comment]
Feel free to merge anytime.

**Comment by grzuy** [comment]
Added some more coverage.
Leaving at this for now, probably a good start.

Will add more in follow up PRs probably.

**Comment by grzuy** [comment]
> Feel free to merge anytime.

Thanks, but don't have write access :-)

**Comment by Narsil** [comment]
Thanks a lot for this.

**Pull request merged**
