### PR TITLE
Add a --seed argument to the stable-diffusion example.

### PR DESCRIPTION
**Pull request by niklasha**
Per suggestion in https://github.com/huggingface/candle/pull/1811#issuecomment-1983079119

### CODE REVIEW

**Review by ivarflakstad — APPROVED** [review]
👌

**Comment by LaurentMazare** [comment]
I don't think this version would work, `set_seed` fail on CPU currently so we would have to check on the device. I might be missing something though, so please test on CPU and whatever GPU you have to check that it works as expected.

**Comment by niklasha** [comment]
> I don't think this version would work, `set_seed` fail on CPU currently so we would have to check on the device. I might be missing something though, so please test on CPU and whatever GPU you have to check that it works as expected.

Yes I was actually aware of that, but just forgot, let me get back with a check for it.

**Review by LaurentMazare — APPROVED** [review]

**Comment by LaurentMazare** [comment]
Thanks!

**Pull request merged**
