### PR TITLE
Derive Clone trait on LogitsProcessor

### PR DESCRIPTION
**Pull request by dan-ilin**

### CODE REVIEW

**Comment by LaurentMazare** [comment]
Could you ellaborate a bit on the use case for this to be cloneable? I'm a little afraid of cloning the rng state as this may result in unexpected behavior but maybe that's something that you would need somehow?

**Comment by dan-ilin** [comment]
@LaurentMazare sure. The use case is to allow it be cloneable so that multiple threads can use their own instance of the `LogitsProcessor ` and not interfere with each other's internal state.

**Comment by LaurentMazare** [comment]
But that wouldn't work well with the rng then, the threads are likely to generate the exact same thing based on the same prompt. Couldn't you create a separate instance per thread? That's likely to be less error prone.

**Comment by dan-ilin** [comment]
Fair enough. I'll go with that approach.

**Pull request closed without merging**
