### PR TITLE
bert attention mask

### PR DESCRIPTION
**Pull request by lz1998**

### CODE REVIEW

**Comment by lz1998** [comment]
Is there something like `torch.finfo(dtype).min` in candle?

**Comment by unlimitedsola** [comment]
Probably a duplicate of #1799

**Comment by EricLBuehler** [comment]
> Is there something like torch.finfo(dtype).min in candle?

@lz1998, you can use `f32::NEG_INFINITY` and then cast to the correct Tensor type.

**Comment by kczimm** [comment]
What's the status of this PR? I've noticed that this PR is necessary to match the output of `transformers` or `sentence_transformers` when batch inputs are of different token length.

**Comment by harryfei** [comment]
+1 for this. Please merge it. @LaurentMazare

**Comment by LaurentMazare** [comment]
Merged, thanks and sorry for the delay.

**Pull request merged**
